### ISSUE TITLE
Can't import the module error on line 45

### ISSUE THREAD

**Issue by poiriersimon** [pcgeek86/elgato#1]
At C:\Users\sipoirie\OneDrive - Microsoft\Documents\WindowsPowerShell\Modules\elgato\0.2\elgato.psm1:45 char:26
+                 On = $On ? 1 : 0
+                          ~
Unexpected token '?' in expression or statement.
At C:\Users\sipoirie\OneDrive - Microsoft\Documents\WindowsPowerShell\Modules\elgato\0.2\elgato.psm1:45 char:25
+                 On = $On ? 1 : 0
+                         ~
The hash literal was incomplete.
At C:\Users\sipoirie\OneDrive - Microsoft\Documents\WindowsPowerShell\Modules\elgato\0.2\elgato.psm1:46 char:13
+             }
+             ~
Missing closing ')' in subexpression.
At C:\Users\sipoirie\OneDrive - Microsoft\Documents\WindowsPowerShell\Modules\elgato\0.2\elgato.psm1:1 char:29
+ function Set-ElgatoKeyLight {
+                             ~
Missing closing '}' in statement block or type definition.
At C:\Users\sipoirie\OneDrive - Microsoft\Documents\WindowsPowerShell\Modules\elgato\0.2\elgato.psm1:47 char:9
+         )
+         ~
Unexpected token ')' in expression or statement.
At C:\Users\sipoirie\OneDrive - Microsoft\Documents\WindowsPowerShell\Modules\elgato\0.2\elgato.psm1:48 char:5
+     } | ConvertTo-Json
+     ~
Unexpected token '}' in expression or statement.
At C:\Users\sipoirie\OneDrive - Microsoft\Documents\WindowsPowerShell\Modules\elgato\0.2\elgato.psm1:48 char:7
+     } | ConvertTo-Json
+       ~
An empty pipe element is not allowed.
At C:\Users\sipoirie\OneDrive - Microsoft\Documents\WindowsPowerShell\Modules\elgato\0.2\elgato.psm1:51 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

Import-Module : The module to process 'elgato.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest
'C:\Users\sipoirie\OneDrive - Microsoft\Documents\WindowsPowerShell\Modules\elgato\0.2\elgato.psd1' was not processed
because no valid module was found in any module directory.
At line:1 char:1
+ Import-Module elgato
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (elgato:String) [Import-Module], PSInvalidOperationException
    + FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by poiriersimon** [comment]
This is I lazy fix the code but I still have issue as if it can be 1 or 0 the light will always go off but the state in the control center is on or off 

if($On){$Power = 1}else{$Power = 0}
    $Body = @{
        NumberOfLights = 1
        Lights = @(
            @{
                Brightness = $Brightness
                Temperature = $Temperature
                On = $Power
            }
        )

**Comment by pcgeek86** [comment]
Hi Simon, I would recommend either uninstalling Control Center or disabling it in your Windows startup tasks. It sounds like Control Center is conflicting with, and overriding the direct API interface.

Let me see if I can fix the import error.

**Comment by pcgeek86** [comment]
I can't seem to reproduce the import error you're seeing on PowerShell version 7.0.3. Which version of PowerShell are you using? 

Keep in mind that the ternary operator is only available in PowerShell version 7, so that's probably why you're getting that error. I can set the minimum version of PowerShell in the manifest.

**Comment by poiriersimon** [comment]
PSVersion                      5.1.19041.1

Let my try on PS 7.0.3

Simon

**Comment by pcgeek86** [comment]
I fixed the minimum PowerShell version in this commit: https://github.com/pcgeek86/elgato/commit/f7a4d08ac64a9d9148c4ac12321ce7a3e434fdc1

Now on PowerShell 5.1 Desktop Edition, you'll see this error message.

```
ipmo : The version of Windows PowerShell on this computer is '5.1.19041.1'. The module 'C:\Users\TrevorSullivan\git\elgato\elgato.psd1' requires a minimum Windows PowerShell version of '7.0' to run. Verify that you have the minimum required version of Windows PowerShell installed, and then try again.
At line:1 char:1
+ ipmo .\elgato.psd1
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\Trevor...ato\elgato.psd1:String) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : Modules_InsufficientPowerShellVersion,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by pcgeek86** [comment]
The easiest way to get PowerShell version 7 is to `docker pull microsoft/powershell`, assuming you have Docker Desktop installed. I look forward to hearing your results. Thanks for reporting the issue, by the way!

**Comment by poiriersimon** [comment]
Powershell 7 seem to import just fine, maybe add the #requirement to the
module
Simon

**Comment by pcgeek86** [comment]
Yup, it's already in the module manifest. Thanks for confirming.
