### ISSUE TITLE
Temperature value

### ISSUE THREAD

**Issue by ChristopheCVB** [pcgeek86/elgato#2]
Hi there!

Do you have any idea how to convert the int value for the temperature to Kelvin and back to that int ?
It's really unclear to me what is the type of that int :/

Thx!

**Comment by m3Labs-io** [comment]
It looks like the color temperature is being defined in 'mired' units, see [Mired\[wikipedia\]](https://en.wikipedia.org/wiki/Mired).

It's derived by dividing 1 million by the temperature in kelvin.

**Comment by jaapbrasser** [comment]
Cool, I've submitted a PR to resolve this. I should probably alter it in the output as well, as the output currently still displays in mired.
